### ISSUE TITLE
please update the two dependencies in actix-connect

### ISSUE THREAD

**Issue by Silentdoer** [actix/actix-net#101]
trust-dns-proto = "=0.18.0-alpha.2"
trust-dns-resolver = "=0.18.0-alpha.2"

**Comment by Jonathas-Conceicao** [comment]
I have a WIP migration ready on [a branch of mine](https://github.com/Jonathas-Conceicao/actix-net/tree/topic/upgrade_trust_dns) but there are a couple of things to be fixed and it would be nice to have someone from the @actix/contributors or the community in geral to opt in on it.

I would't mind creating a PR in case anyone thinks it would be easier to make the discussion there. 

### 1. Handle Result from `AsyncResolver::new`
The first point is that the new `AsyncResolver` provided by trust-dns-resolver returns a result when trying to build with a given config. If this fails should we (a) propagate the the error to the caller? (b) Start the resolver with the default config? Or should we (c) panic with a proper message, i.e., use `expect`?

Since this will already introduce a breaking change I believe that (a) is the best way to handle this. 

### 2. `Service::call` for `Resolver<T>`

As creating a new `AsyncResolver` will now be an async function, the `Service::call` implementation for `Resolver<T>` becomes more tricky. That's because it involves updating the internal state of the `Resolver` if the internal `AsyncResolver` as not beeing set yet, but as this future is returned, handling the lifetime to the `Resolver` itself becomes tricky.

What I currently have  is that I don't update the internal state of the `Resolver` on the `Service::call`, so if it's called without a `AsyncResolver` already set, it will always create a new one. This seams to work but I'm not sure if it's ideal.

**Comment by ignatenkobrain** [comment]
This is necessary to update actix stack in Fedora... I believe this was already done for Actix itself, so this probably should not be very complicated.

**Comment by ignatenkobrain** [comment]
@Jonathas-Conceicao regarding point 1, I think (a) is the best.
