### ISSUE TITLE
Create more example apps

### ISSUE THREAD

**Issue by uzytkownik** [actix/actix-net#18]
I'm trying to understand how to use `actix-net` to write simple networking code. However due to being unfamiliar with the nomenclature it is hard to navigate the documentation.

It might help to have (my guess is based on features I think are in):
 - Line-based echo application (I guess it might allow to present transformation from bytes to strings and from strings to lines?)
 - Line-based chat server (above + reply to clients not directed at their request)

**Comment by fafhrd91** [comment]
i dont think line-base echo makes much sense, most of the code would be in tokio-io codec.

proper example is [actix-mqtt](https://github.com/actix/actix-mqtt)

**Comment by uzytkownik** [comment]
> proper example is actix-mqtt

I think actix-mqtt is a bit too large and too 'production' product to be a useful example. At least for me it requires understending actix-net AND mqtt...

> i dont think line-base echo makes much sense, most of the code would be in tokio-io codec.

As long as it shows the API usage that should be fine? Especially if it can be moved to separate module (and I presume tokio-io codec is important for chaining the services?).

That said I have trouble figuring out what actix-net is exactly doing so the examples are based on my guesses based on README.

**Comment by cdbattags** [comment]
Another great set of examples can be found here:

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Rust/actix

**Comment by volundmush** [comment]
I am hoping to create a MUD server and am investigating actix-net.

This is going to require a Telnet server. However, it's increasingly common for MUD servers to offer a TLS-protected telnet port.

Have been scratching my head for hours trying to figure out how exactly actix-server's ServerBuilder.bind() and ServiceFactory-related things interact with everything. Is TLS support some kind of middleware? I've been tearing apart this code and yet I don't follow what the END RESULT is supposed to be, because the Examples under basic.rs and ssl.rs are TOO simple - they accept the connection, but don't really... connect it to anything.

Not even an echo service.

It is definitely slowing me down.

**Comment by efx** [comment]
I'm finding https://github.com/actix/examples especially helpful for seeing how to build real things using actix.
@uzytkownik would you say the linked project addresses your core frustration?

**Comment by robjtede** [comment]
there's a couple examples in here now:
https://github.com/actix/actix-net/tree/master/actix-server/examples
