### ISSUE TITLE
Drop tokio-openssl, use custom impl

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-net#63]
tokio-openssl is designed for async/await usage, it is not very friendly for low level code

**Comment by tyranron** [comment]
The same is with `tokio-tls`, the problem is that they both use `async fn` and does not return named `Future` (while `tokio-rustls` is good 😊).

I've created https://github.com/alexcrichton/tokio-openssl/issues/15 to try to handle it first on the lib side.

The same question I've asked in Tokio Discord chat about `tokio-tls` and Tokio devs don't mind about such change. I'll try to rollout that changes during weekends.

**Comment by kanekv** [comment]
How do we want to approach this? Try to get a patch into tokio-openssl?

**Comment by fafhrd91** [comment]
Seems tokio-openssl does not have any interest in ticket. I’d create custom futures in actix-service/connect and then submit pr to tokio-openssl

**Comment by fakeshadow** [comment]
tokio-openssl 0.6 introduced a whole set of poll based API so I think this PR can be closed.
