### ISSUE TITLE
Switch AppVeyor to GitHub Actions

### ISSUE THREAD

**Issue by JohnTitor** [actix/actix-net#70]
It'd be nice to run CI on Windows to avoid build failures. And I think we can try it with GitHub Actions to make CI fast.

**Comment by JohnTitor** [comment]
Current status:
- macOS: failed in test
- Windows: failed to install `openssl-sys`

**Comment by klmallory** [comment]
adding to this, I am unable to build in alpha.2 on windows...

error[E0432]: unresolved import `self::unix`
  --> C:\Users\Me\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-rt-1.0.0-alpha.2\src/lib.rs:56:19
   |
56 |     pub use self::unix::*;
   |                   ^^^^ could not find `unix` in `self`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `actix-rt`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by JohnTitor** [comment]
@klmallory It has been fixed in `1.0.0-alpha.3`.

**Comment by fafhrd91** [comment]
ci action works
